[build]
  publish = "."

[[redirects]]
  from = "/monitoring"
  to = "/monitoring.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
